# Generated by Django 3.2.6 on 2021-09-04 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_use_email_verify_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeuser',
            name='profile',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile'),
            preserve_default=False,
        ),
    ]
