# Generated by Django 3.2.6 on 2021-09-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210905_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuser',
            name='mobile',
        ),
    ]
