# Generated by Django 3.2.6 on 2021-09-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_customeuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='mobile',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
