# Generated by Django 3.2.6 on 2021-09-15 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customeuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='master',
            field=models.CharField(choices=[('Neurology', 'Neurology'), ('Opthalmology', 'Opthalmology'), ('Nuclear Magnetic', 'Nuclear Magnetic'), ('Surgical', 'Surgical'), ('Cardiology', 'Cardiology'), ('Dental', 'Dental'), ('Traumatology', 'Traumatology'), ('General Surgeon', 'General Surgeon'), ('Medicine Specialists', 'Medicine Specialists'), ('Sports Medicine Specialists', 'Sports Medicine Specialists'), ('Other', 'Other')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeuser',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
