# Generated by Django 3.2.6 on 2021-09-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210915_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeuser',
            old_name='text',
            new_name='clinic',
        ),
        migrations.AddField(
            model_name='customeuser',
            name='some',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
