# Generated by Django 3.2.6 on 2021-09-17 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_doctor_validate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='end_time',
            field=models.TimeField(default=''),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='in_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='out_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='start_time',
            field=models.TimeField(default=''),
        ),
    ]
