# Generated by Django 3.2.6 on 2021-09-17 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210917_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='end_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='start_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
