# Generated by Django 3.2.6 on 2021-09-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210917_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='master',
            field=models.CharField(choices=[('Neurology', 'Neurology'), ('Ophthalmology', 'Ophthalmology'), ('Dermatology', 'Dermatology'), ('Surgical', 'Surgical'), ('Cardiology', 'Cardiology'), ('Dental', 'Dental'), ('Traumatology', 'Traumatology'), ('General Surgeon', 'General Surgeon'), ('Medicine Specialists', 'Medicine Specialists'), ('Sports Medicine Specialists', 'Sports Medicine Specialists'), ('Pediatrics', 'Pediatrics'), ('Nutrition Counselling', 'Nutrition Counselling')], max_length=100),
        ),
    ]
