# Generated by Django 3.2.6 on 2021-09-14 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualified',
            name='fdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualified',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
