# Generated by Django 3.2.6 on 2021-09-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_pat_inqu_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
