# Generated by Django 3.2.6 on 2021-09-18 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0005_delete_doctors_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=100)),
                ('when', models.DateField()),
                ('patient', models.CharField(max_length=100)),
                ('pro', models.ImageField(upload_to='pat_img')),
                ('gender', models.CharField(max_length=100)),
                ('fnm', models.CharField(max_length=100)),
                ('lnm', models.CharField(max_length=100)),
                ('phone', models.ImageField(upload_to='')),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
