# Generated by Django 3.2.6 on 2021-09-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_book_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_app',
            name='pro',
        ),
    ]
