# Generated by Django 3.2.6 on 2021-09-18 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_remove_book_app_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_app',
            name='add',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_app',
            name='doc_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_app',
            name='mast',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_app',
            name='ph',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_app',
            name='dob',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book_app',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
