# Generated by Django 3.2.6 on 2021-09-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20210918_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_app',
            name='add',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book_app',
            name='doc_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book_app',
            name='mast',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book_app',
            name='ph',
            field=models.CharField(default='', max_length=100),
        ),
    ]
