# Generated by Django 3.2.6 on 2021-09-19 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20210918_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_app',
            name='end_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book_app',
            name='fdate',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_app',
            name='in_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book_app',
            name='out_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book_app',
            name='pro',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pat_img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_app',
            name='start_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
