# Generated by Django 3.2.6 on 2021-09-19 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_auto_20210919_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_app',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='doc_img'),
            preserve_default=False,
        ),
    ]
