# Generated by Django 3.2.6 on 2021-09-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20210925_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='select',
            field=models.CharField(max_length=100),
        ),
    ]
