# Generated by Django 3.2.6 on 2021-09-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_alter_feedback_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
