# Generated by Django 3.2.6 on 2021-09-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_alter_feedback_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_app',
            name='disease',
            field=models.CharField(default='', max_length=100),
        ),
    ]
