# Generated by Django 3.2.6 on 2021-09-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_alter_book_app_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_app',
            name='disease',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
