# Generated by Django 3.2.6 on 2021-09-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_remove_book_app_do_this'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_app',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
