# Generated by Django 3.2.6 on 2021-09-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0023_alter_book_app_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_app',
            name='five',
        ),
        migrations.RemoveField(
            model_name='book_app',
            name='four',
        ),
        migrations.RemoveField(
            model_name='book_app',
            name='link',
        ),
        migrations.RemoveField(
            model_name='book_app',
            name='one',
        ),
        migrations.RemoveField(
            model_name='book_app',
            name='three',
        ),
        migrations.RemoveField(
            model_name='book_app',
            name='two',
        ),
    ]
