# Generated by Django 3.2.6 on 2021-10-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_auto_20210930_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_app',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
