# Generated by Django 3.2.6 on 2021-09-12 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doc_data',
        ),
    ]
