# Generated by Django 3.2.6 on 2021-09-12 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0003_doc_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_info',
            name='doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doc_info',
            name='master',
            field=models.CharField(choices=[('Neurology', 'Neurology'), ('Opthalmology', 'Opthalmology'), ('Nuclear Magnetic', 'Nuclear Magnetic'), ('Surgical', 'Surgical'), ('Cardiology', 'Cardiology'), ('Dental', 'Dental'), ('Traumatology', 'Traumatology'), ('General Surgeon', 'General Surgeon'), ('Medicine Specialists', 'Medicine Specialists'), ('Sports Medicine Specialists', 'Sports Medicine Specialists'), ('Other', 'Other')], max_length=100),
        ),
    ]
