# Generated by Django 3.2.6 on 2021-09-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_doc_info_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc_info',
            name='doctor',
        ),
    ]
