# Generated by Django 3.2.6 on 2021-09-14 13:42

from django.db import migrations
import django.utils.timezone
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
