# Generated by Django 3.2.6 on 2021-09-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_post_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doc_info',
        ),
    ]
