# Generated by Django 3.2.6 on 2021-09-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_delete_doc_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_time',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
