# Generated by Django 3.2.6 on 2021-09-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_alter_doc_time_end_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoint',
        ),
    ]
