# Generated by Django 3.2.6 on 2021-10-02 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_treatment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
