# Generated by Django 3.2.6 on 2021-10-02 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='doc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='doc_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='fdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='master',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='when',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
