# Generated by Django 3.2.6 on 2021-10-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_auto_20211002_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
