# Generated by Django 3.2.6 on 2021-10-05 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_alter_treatment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='four',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='treatment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
