# Generated by Django 3.2.6 on 2021-10-05 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_auto_20211005_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='doc_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='doc_pic'),
            preserve_default=False,
        ),
    ]
