# Generated by Django 3.2.6 on 2021-10-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0024_treatment_doc_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='pat_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
